//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlicerConf.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Picture
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public byte[] img { get; set; }
        public int PrinterId { get; set; }
        public int FilamentId { get; set; }
        public int PrinterSettingId { get; set; }
    
        public virtual Printer Printer { get; set; }
        public virtual Filament Filament { get; set; }
        public virtual PrinterSetting PrinterSetting { get; set; }
    }
}
