//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlicerConf.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SlicerConfDBModelContainer : DbContext
    {
        public SlicerConfDBModelContainer()
            : base("name=SlicerConfDBModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Printer> Printers { get; set; }
        public virtual DbSet<PrinterSetting> PrinterSettings { get; set; }
        public virtual DbSet<Filament> Filaments { get; set; }
        public virtual DbSet<Picture> Pictures { get; set; }
    }
}
